app:
  rabbitmq:
    queues:
      currency-convert-request: CURRENCY_CONVERT_REQUEST_QUEUE

server:
  port: '8080'

spring:
  application:
    name: currency-service
  cloud:
    config:
      fail-fast: 'true'
      retry:
        max-attempts: '30'
      uri: http://localhost:8071
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: '1.0'
  zipkin:
    base-url: http://localhost:9411
