auth_enabled: false
common:
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
ruler:
  alertmanager_url: http://localhost:9093
schema_config:
  configs:
    - from: 2020-10-24
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v11
      store: boltdb-shipper
server:
  grpc_listen_port: 9096
  http_listen_port: 3100
