spring:
  config:
    location: http://localhost:8071
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTION
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,prometheus
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8079

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG

gateway-config:
  secured-get-paths:
  #    - /api/v1/car/**
  #    - /api/v1/car
  #    - /api/v1/car/findByStatus
  #    - /api/v1/currency
  #    - /api/v1/currency/**
  #    - /api/v1/opening-hours
  #    - /api/v1/opening-hours/**
  #    - /api/v1/location/**
  #    - /api/v1/location
  secured-post-paths:
    - /api/v1/order
    - /api/v1/auth/admin
    - /api/v1/auth/order
