server:
  port: '8071'

spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/caf3babe/mat-app-config.git
  profiles:
    active: git
