logstash:
  logstashPipeline:
  logstash.conf: |-
    input {
      tcp {
        codec => json_lines
      }
    }

    filter {
      mutate {
        add_tag => [ "car-rental-microservices" ]
      }
    }

    output {
      elasticsearch {
        hosts => "zipkin-elasticsearch-master:9200"
      }
    }