replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-currency-service:main
  pullPolicy: Always
  tag: ""

imagePullSecrets: 
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: spring_profiles_active
    value: "prod"
  - name: spring_cloud_config_uri
    value: http://car-rental-configuration-service:8071

mongodb:
  nameOverride: currency-service-db
  auth:
    rootPassword: example