car-rental-app:
  admin:
    email: admin
    password: admin123
  jwt-secret: sWDXQcubDCnNsll7DoE6s9H2idu/oQoZQJ0eVoRZCN1uLuWE2SCXd3jPdyu3tIBp

server:
  port: 8085

spring:
  application:
    name: authentication-service
  cloud:
    config:
      uri: http://localhost:8071
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
