server:
  port: 8070
spring:
  application:
    name: discovery-service
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 30
      uri: http://localhost:8071
  profiles:
    active: dev
