app:
  rabbitmq:
    queues:
      location-created: LOCATION_CREATED_QUEUE
      location-finished: LOCATION_FINISHED_QUEUE
      location-rejected: LOCATION_REJECTED_QUEUE

server:
  port: '8081'
spring:
  application:
    name: opening-hours-service
  cloud:
    config:
      fail-fast: 'true'
      retry:
        max-attempts: '30'
      uri: http://localhost:8071
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: '1.0'
  zipkin:
    base-url: http://localhost:9411
