env:
  IMAGE_NAME: ${{ github.repository }}
  MICRO_SERVICE: order-service
  REGISTRY: ghcr.io
jobs:
  build-and-push:
    name: Build and Push to Packages
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ env.MICRO_SERVICE }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ env.MICRO_SERVICE }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
name: Order Service
on:
  push:
    branches: [main]
    paths:
      - order-service/**
      - .github/workflows/order-service.yml
